[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "compress"
version = "0.2"
authors = [
  { name = "Laurens Devos" }, { name = "Timo Martens" }
]
description = "Compressing Tree Ensembles through Level-wise Optimization and Pruning"
readme = "README.md"
requires-python = ">=3.10, < 3.11"
dependencies = [
    "numpy >= 1.26, < 2",
    "scikit-learn >= 1.4",
    "scipy >= 1.12",
    "dtai-veritas >= 0.2",
    "colorama",
    "xgboost >= 2.1.3, < 3",
    "prada @ git+https://github.com/laudv/prada.git@main",
    "tqdm >= 4.67",
    "matplotlib >= 3.10",
    "numba >= 0.60"

]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/ML-KULeuven/lop_compress"
Issues = "https://github.com/ML-KULeuven/lop_compress/issues"
